language: node_js

node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
    - bash ./bin/build.sh

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: git@github.com:zoncoen/hugo_theme_pickles.git
