language: node_js

node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
    - bash ./bin/build.sh

after_success: bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/zoncoen/hugo_theme_pickles.git
  - secure: "FG+DiCHS+Nt7q3hJCctt96DQIUPHBX59kj14SNNbGt+UcmWklYeeseagWqJBgpup3kRPkLw9eP8TWzAcr+lteAam47R4ytw/HZcYWiEF58Gr/YQEEEbYW9xwrFdHMjJN+H8sK0ZKHzr8bUgCXnqwdUUO2PNKADOiXBY91WFkX/v3fhn45t5wAlGlNFZCH7TvshF2TXgQPv04vzGr9YPhtscdxRGkIA+otZ8zMfprya5XgymkUhg/ipEwgVPts/YPmPWvEZzwXuCaEekflKgHKPONGZnSHFpqjZmlVzSNvwOfJMahy9ogvBvBLpSM7bjTVvihBVJHd0CjFaxbmZvJc3IisTjstCb4pj0KFskfupymuA2255wZyqPZXr68QMpLOcNDxErX1/qpqpTeNByzZVvreO5Tuo3QL9gEMowE7tSjy183b7bNrMaGQePzvWBCdzIYri1RDM1M7sG2w6uSGdfWURA+MR9xLAfMKPb38El5XJLFGmG3UZmIDIF/M0wqvxw0YNfIf3Y6hmCLOymfELIiUzpm2RIcZDcsM35PfUyCffYUDphghuK/XK3geaK4D98kYmFBuOUGvC2xis3+bsVR3uYXjLJJYXOZiFUoKVmvXOSJHgRwuEK8o3lm1CxEArB67ncw179jKC1cqVbzXoVqciw4kKRgDHVryt6TOFQ="
